import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/Providers";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import AnnouncementBar from "@/components/common/AnnouncementBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "TurboTreats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <Providers>
          <div className="min-h-screen bg-white">
            <div className="w-full px-1 lg:px-4 bg-white">
              <AnnouncementBar />
              <Navbar />
              {children}
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
